#!/usr/bin/env zsh

source $CONFIG_DIR/env.sh # Loads all defined colors

# bar props and defaults
source $CONFIG_DIR/sketchy_defaults.sh
source $CONFIG_DIR/aerospaces.sh
source $ITEM_DIR/apple.sh
source $ITEM_DIR/clock.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/disk.sh
source $ITEM_DIR/battery.sh


##### Finalizing Setup #####
sketchybar --update
sketchybar --hotload true
