#!/usr/bin/env zsh

# https://github.com/FelixKratz/dotfiles
# https://felixkratz.github.io/SketchyBar/config/bar

source "$CONFIG_DIR/env.sh" # Loads all defined colors


# bar props and defaults
source "$CONFIG_DIR/sketchy_defaults.sh"
# source "$CONFIG_DIR/aerospaces.sh"

# HACK - Left is Top when bar is displayed vertically

##### Left Side Items #####
# these are now top items
# starting at top-most
# source $ITEM_DIR/aerospace_spaces.sh
# source $ITEM_DIR/aerospace_controls.sh

# load helpers for aerospace
# source "$PLUGIN_DIR/aerospace.sh"

##### Left Side Of Notch Items #####
# not relevant on vertical layout

##### Right Side Of Notch Items #####
# not relevant on vertical layout

##### Right Side Items #####
# these are now bottom items
# starting at bottom-most

source $ITEM_DIR/apple.sh
source $ITEM_DIR/clock.sh
# source $ITEM_DIR/outdated.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/disk.sh
# source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
# source $ITEM_DIR/wifi.sh

source "$CONFIG_DIR/sketch_aero.sh"
sketchybar --add event aerospace_workspace_change

# need swap monitor if needed
count_monitors=$(aerospace list-monitors | wc -l)
[[ "$count_monitors" -eq 2 ]] && need_swap_monitor=true

divider_every=4
divider_count=0

for monitor_ in $(aerospace list-monitors | awk '{print $1}'); do
  monitor="$monitor_"
  if [[ "$need_swap_monitor" == true ]]; then
    [[ "$monitor_" == 1 ]] && monitor="2"
    [[ "$monitor_" == 2 ]] && monitor="1"
  fi

  for sid in $(aerospace list-workspaces --monitor "$monitor_"); do
    sketchybar --add item "space.$sid" left \
      --subscribe space.$sid aerospace_workspace_change \
      --set "space.$sid" \
        display="$monitor" \
        width=30 \
        icon.padding_right=0 \
        icon.padding_left=0 \
        label=$sid \
        label.width=30 \
        label.color=0xFFFFFFFF \
        label.font="IBM Plex Mono:Semibold:14.0" \
        label.align="center" \
        background.color=0xFFF17013 \
        background.height=30 \
        icon.font="sketchybar-app-font:Regular:5.0" \
        icon.color=0xFFFFFFFF \
        script="$CONFIG_DIR/sketch_aero.sh $sid" \



    local json_items=$(aerospace list-windows --workspace "$sid" --json --format %{monitor-id}%{workspace}%{app-bundle-id}%{window-id}%{app-name})
    # Get Aerospace Windows JSON
    if ! echo "$json_items" | jq -e '.' >/dev/null 2>&1; then
      echo "Invalid JSON from Aerospace" >&2
      continue
    fi

    count=$(jq length <<< "$json_items" 2>/dev/null || echo 0)
    [[ ! "$count" =~ ^[0-9]+$ ]] && continue

    for ((i = 0; i < count; i++)); do
      workspace=$(jq -r --argjson i "$i" '.[$i]["workspace"] // empty' <<< "$json_items")
      app_name=$(jq -r --argjson i "$i" '.[$i]["app-name"] // empty' <<< "$json_items")
      window_id=$(jq -r --argjson i "$i" '.[$i]["window-id"] // empty' <<< "$json_items")
      monitor_id=$(jq -r --argjson i "$i" '.[$i]["monitor-id"] // empty' <<< "$json_items")
      # echo "Workspace: $workspace"
      # echo "SID: $sid"
      # echo "App Name: $app_name"
      echo "--------------------------"
      [[ "$workspace" != "$sid" ]] && continue
      [[ -z "$app_name" ]] && continue

      icon="$($CONFIG_DIR/icons_apps.sh "$app_name")"
      # echo "Processing: App=$app_name, Icon=$icon, Workspace=$workspace Monitor=$monitor_id Window=$window_id"
      

      echo "end------------------"
      # Add to SketchyBar with window ID to prevent overwriting
      sketchybar --add item "app.$sid.$window_id" left \
        --set "app.$sid.$window_id" \
        display="$monitor" \
        width=30 \
        icon.padding_right=0 \
        icon.padding_left=0 \
        label.padding_left=0 \
        label.padding_right=0 \
        background.color=0xFFFFFFFF \
        background.height=30 \
        icon="$icon" \
        icon.width=30 \
        icon.font="sketchybar-app-font:Regular:14.0" 
    done
    
    divider_count=$((divider_count + 1))
    if [[ $((divider_count % divider_every)) -eq 0 ]]; then
      echo "Adding Divider"
      sketchybar --add item "divider.$sid.$divider_count" left  \
        --set "divider.$sid.$divider_count" \
        width=20 \
        background.padding_left=10 \
        background.height=1 \
        background.padding_right=-30 \
        background.color=0xFFFFFFFF \
        background.y_offset=0 \
        background.corner_radius=0 \
        icon.padding_right=0 \
        icon.padding_left=0 \
        label.padding_left=0 \
        label.padding_right=0 \
        display="$monitor" 
    fi


  done
done

##### Finalizing Setup #####
sketchybar --update
sketchybar --hotload true
