#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SECRETS_FILE="$HOME/.secrets"
TEMPLATE_FILE="$SCRIPT_DIR/../zsh/.secrets.example"
QUIET=0
FORCE=0
FROM_FILE=""

usage() {
  cat <<'EOF'
Usage: ./__scripts__/restore_credentials.sh [--quiet] [--force] [--from-file <path>]

  --quiet              Reduce output
  --force              Overwrite existing ~/.secrets
  --from-file <path>   Copy a prepared secrets file into ~/.secrets
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --quiet)
      QUIET=1
      ;;
    --force)
      FORCE=1
      ;;
    --from-file)
      shift
      FROM_FILE="${1:-}"
      if [ -z "$FROM_FILE" ]; then
        printf '[restore-credentials] --from-file requires a path\n' >&2
        exit 1
      fi
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf '[restore-credentials] unknown argument: %s\n' "$1" >&2
      usage >&2
      exit 1
      ;;
  esac
  shift
done

log() {
  if [ "$QUIET" -eq 0 ]; then
    printf '[restore-credentials] %s\n' "$*"
  fi
}

mappings=(
  "OPENAI_API_KEY:openai/api-key"
  "OPENCODE_API_KEY:opencode/api-key"
  "ANTHROPIC_API_KEY:anthropic/api-key"
  "GOOGLE_API_KEY:google/api-key"
  "GITHUB_TOKEN:github/token"
)

if [ -n "$FROM_FILE" ]; then
  src_file="$FROM_FILE"
  if [ ! -f "$src_file" ]; then
    printf '[restore-credentials] source file not found: %s\n' "$src_file" >&2
    exit 1
  fi

  if [ -f "$SECRETS_FILE" ] && [ "$FORCE" -ne 1 ]; then
    log 'Existing ~/.secrets found. Use --force to overwrite.'
    exit 0
  fi

  cp "$src_file" "$SECRETS_FILE"
  chmod 600 "$SECRETS_FILE"
  log 'Restored ~/.secrets from --from-file source.'
  exit 0
fi

if [ ! -f "$TEMPLATE_FILE" ]; then
  log "Template not found: $TEMPLATE_FILE"
  exit 0
fi

source_mode="none"
if command -v pass >/dev/null 2>&1 && pass ls >/dev/null 2>&1; then
  source_mode="pass"
else
  has_env=0
  for item in "${mappings[@]}"; do
    env_name="${item%%:*}"
    if [ -n "${!env_name:-}" ]; then
      has_env=1
      break
    fi
  done
  if [ "$has_env" -eq 1 ]; then
    source_mode="env"
  fi
fi

if [ "$source_mode" = "none" ]; then
  if [ ! -f "$SECRETS_FILE" ]; then
    cp "$TEMPLATE_FILE" "$SECRETS_FILE"
    chmod 600 "$SECRETS_FILE"
    log 'Created ~/.secrets from template.'
  else
    log 'No pass/env credentials found; keeping existing ~/.secrets.'
  fi
  exit 0
fi

if [ -f "$SECRETS_FILE" ] && [ "$FORCE" -ne 1 ]; then
  log 'Existing ~/.secrets found. Use --force to regenerate from pass/env.'
  exit 0
fi

tmp_file="$(mktemp)"
{
  printf '# Generated by __scripts__/restore_credentials.sh\n'
  if [ "$source_mode" = "pass" ]; then
    printf '# Source mode: pass\n\n'
  else
    printf '# Source mode: environment variables\n\n'
  fi

  for item in "${mappings[@]}"; do
    env_name="${item%%:*}"
    pass_path="${item#*:}"
    value=""

    if [ "$source_mode" = "pass" ]; then
      raw_value="$(pass show "$pass_path" 2>/dev/null || true)"
      if [ -n "$raw_value" ]; then
        value="${raw_value%%$'\n'*}"
      fi
    fi

    if [ -z "$value" ] && [ -n "${!env_name:-}" ]; then
      value="${!env_name}"
    fi

    if [ -n "$value" ]; then
      printf 'export %s=%q\n' "$env_name" "$value"
    else
      printf '# export %s=""\n' "$env_name"
    fi
  done
} > "$tmp_file"

mv "$tmp_file" "$SECRETS_FILE"
chmod 600 "$SECRETS_FILE"
log "Restored ~/.secrets using $source_mode source."
